version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  load:
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          name: Restore NodeJS Modules and Yarn Cache
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          name: Store NodeJS Modules and Yarn Cache
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~\AppData\Local\Yarn\Cache
            - ./node_modules
  test:
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Lint
          command: yarn lint
      - run:
          name: Run Unit Tests
          command: yarn electron:test:unit
      - store_test_results:
          name: Store Test Results
          path: reports/junit
      - store_artifacts:
          name: Store Coverage Reports
          path: reports/coverage/lcov-report
          destination: coverage

  build:
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn electron:build
      - store_artifacts:
          name: Store Coverage Reports
          path: dist_electron/win-unpacked
          destination: coverage

workflows:
  version: 2
  execute:
    jobs:
      - load
      - test:
          requires:
            - load
      - build:
          requires:
            - test
