version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.1
workflows:
  build:
    jobs:
    - cypress/run:
        yarn: true
        no-workspace: true

        command: yarn test:unit

        post-steps:
          - store_artifacts:
              path: coverage
