version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  load:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          name: Save Yarn Cache
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~\AppData\Local\Yarn\Cache
  test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Lint
          command: yarn lint
      - run:
          name: Run Unit Tests
          command: yarn electron:test:unit
      - store_test_results:
          name: Store Test Results
          path: reports/junit
      - store_artifacts:
          name: Store Coverage Reports
          path: reports/coverage/lcov-report
          destination: coverage

  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn electron:build
      - persist_to_workspace:
          root: .
          paths:
            - dist_electron

  package:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install WiX Toolset
          command: choco install wixtoolset 
      - persist_to_workspace:
          root: .
          paths:
            - dist_electron
      - store_artifacts:
          path: C:\ProgramData\chocolatey\logs
          destination: chocolatey_logs

workflows:
  version: 2
  execute:
    jobs:
      - load
      - test:
          requires:
            - load
      - build:
          requires:
            - test
      - package:
          requires:
            - build
