version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    docker:
    - image: circleci/node:13.7.0-browsers

    steps:
      - checkout
      - node/with-cache:
          steps:
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                  - yarn-packages-{{ checksum "yarn.lock" }}

            - run:
                name: Install
                command: yarn install --frozen-lockfile

            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                  - ~/.cache/yarn

            - run:
                name: Run Lint
                command: yarn lint

            - run:
                name: Run Unit Tests
                command: yarn electron:test:unit

            - store_test_results:
                name: Store Test Results
                path: junit.xml

            - store_artifacts:
                name: Store Coverage Artifact
                path: coverage
                destination: coverage

workflows:
    build-and-test:
      jobs:
        - build-and-test
