export default {
  application: {
    background: 'background',
    surface: 'surface',
    primary: 'primary',
    secondary: 'secondary',
    accent: 'accent',
    error: 'error',
    info: 'info',
    warning: 'warning',
    success: 'success',
  },
  rendered: {
    background: 'rendered-background',
    header_1: 'rendered-header-1',
    header_2: 'rendered-header-2',
    header_3: 'rendered-header-3',
    header_4: 'rendered-header-4',
    header_5: 'rendered-header-5',
    header_6: 'rendered-header-6',
    content: 'rendered-content',
    anchor: 'rendered-anchor',
    selection: 'rendered-selection',
    highlight: 'rendered-highlight',
    highlight_focus: 'rendered-highlight-focus',
  },
  compose: {
    background: 'compose-background',
    gutters: 'compose-gutters',
    line_numbers: 'compose-line-numbers',
    content: 'compose-content',
    comments: 'compose-comments',
    anchor: 'compose-anchor',
    header_1: 'compose-header-1',
    header_2: 'compose-header-2',
    header_3: 'compose-header-3',
    header_4: 'compose-header-4',
    header_5: 'compose-header-5',
    header_6: 'compose-header-6',
    keywords: 'compose-keywords',
    operators: 'compose-operators',
    types: 'compose-types',
    brackets: 'compose-brackets',
    strings: 'compose-strings',
    numbers: 'compose-numbers',
    booleans: 'compose-booleans',
    selection: 'compose-selection',
    highlight: 'compose-highlight',
    highlight_focus: 'compose-highlight-focus',
  },
}
