export default {
  application: {
    background: 'background',
    surface: 'surface',
    primary: 'primary',
    secondary: 'secondary',
    accent: 'accent',
    error: 'error',
    info: 'info',
    warning: 'warning',
    success: 'success',
  },
  rendered: {
    background: 'rendered-background',
    header_1: 'rendered-header-1',
    header_2: 'rendered-header-2',
    header_3: 'rendered-header-3',
    header_4: 'rendered-header-4',
    header_5: 'rendered-header-5',
    header_6: 'rendered-header-6',
    content: 'rendered-content',
    anchor: 'rendered-anchor',
  },
  compose: {
    background: 'compose-background',
    header_1: 'compose-header-1',
    header_2: 'compose-header-2',
    header_3: 'compose-header-3',
    header_4: 'compose-header-4',
    header_5: 'compose-header-5',
    header_6: 'compose-header-6',
    content: 'compose-content',
    anchor: 'compose-anchor',
    gutters: 'compose-gutters',
    line_numbers: 'compose-line-numbers',
  },
}
