name: build
on: [push, workflow_dispatch]

jobs:
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: feat-layout-add-github-actions   
        
    - uses: actions/setup-node@master
      with:
        node-version: 14.19.1
        
    - name: Instally Python
      run: choco install python2
        
    - name: Install Perl
      run: |
        choco install strawberryperl
        echo ";C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Install NASM
      run: |
        choco install nasm
        echo ";C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
    - name: install node-gyp
      run: npm install --global node-gyp
      
    - name: install Windows Build Tools
      run: npm install --global --vs2015 --production windows-build-tools

    - name: Set NPM to use Python 2.7
      run: npm config set python python2.7
      
    - name: Set NPM to use Visual Studio 2015
      run: npm config set msvs_version 2015

    - name: Install dependencies
      run: npm install
      
    - name: Build Renderer
      run: npm run build-renderer

    - name: Build packages for Electron
      run: npm run electron-rebuild
  
    - name: Build Installer
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run build
