name: build
on: [push, workflow_dispatch]

jobs:
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: feat-layout-add-github-actions   
        
    - uses: actions/setup-node@master
      with:
        node-version: 14.19.1
        
    - name: Install Python
      run: choco install python2 --version=2.7.15 --params "/InstallDir:$Env:SystemDrive\Python27"

    - name: Set NPM to use Python 2.7
      run: npm config set python C:\Python27\python.exe
        
    - name: Install Perl
      run: |
        choco install strawberryperl
        echo ";C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Install NASM
      run: |
        choco install nasm
        echo ";C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
    - name: Install node-gyp
      run: npm install --global node-gyp@latest
      
    - name: Download Windows Build Tools
      run: curl -SL --output vs_buildtools.exe https://aka.ms/vs/15/release/vs_buildtools.exe
      
    - name: Install Windows Build Tools
#       run: Start-Process "$Env:SystemDrive\vs_buildtools.exe --wait --norestart --nocache --installPath ""${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\BuildTools""" | Invoke-Expression
      run:
        .\vs_buildtools.exe --wait --norestart --passive --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\BuildTools"
        --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools
        --add Microsoft.VisualStudio.Workload.MSBuildTools
      shell: cmd
      
    - name: Debug build tools
      run:  Get-ChildItem "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\BuildTools"
    - name: Debug build tools2
      run:  Get-ChildItem "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\BuildTools\VC"
    - name: Debug build tools3
      run:  Get-ChildItem "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary"
      
    - name: Debug build tools4
      run:  Get-ChildItem "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"
      
    - name: Install dependencies
      run: npm install

    - name: Build packages for Electron
      run: npm run electron-rebuild
      
    - name: Build Renderer
      run: npm run build-renderer
  
    - name: Build Installer
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run build
