name: build
on: [push, workflow_dispatch]

jobs:
  build_on_win:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
      with:
        ref: feat-layout-add-github-actions   
        
    - uses: actions/setup-node@master
      with:
        node-version: 14.19.1
        
    - name: Install Perl
      run:
        choco install perl
        echo ";C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Install NASM
      run:
        choco install nasm
        echo ";C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
    - name: Install node-gyp
      run: npm install --global node-gyp
      
    - name: Install Windows Build Tools
      run: npm install --global --production windows-build-tools@4.0.0

    - name: Install dependencies
      run: npm install
      
    - name: Build Renderer
      run: npm run build-renderer

    - name: Build packages for Electron
      run: npm run electron-rebuild
  
    - name: Build Installer
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run build
