name: build
on: [push, workflow_dispatch]

jobs:
  build_on_win:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
      with:
        ref: feat-layout-add-github-actions   
        
    - uses: actions/setup-node@master
      with:
        node-version: 14.19.1
        
    - name: Install Python
      run: choco install python
        
    - name: Install visualstudio2017-workload-vctools Package
      run: choco install visualstudio2017-workload-vctools
      
    - name: Configure NPM
      run: npm config set msvs_version 2017
      
    - name: install node-gyp
      run: npm install --global node-gyp@latest

    - name: Install dependencies
      run: npm install
      
    - name: Build Renderer
      run: npm run build-renderer

    - name: Build packages for Electron
      run: npm run electron-rebuild
  
    - name: Build Installer
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run build
