name: build
on: [push, workflow_dispatch]

jobs:
  build_on_win:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
      with:
        ref: feat-layout-add-github-actions   
        
    - uses: actions/setup-node@master
      with:
        node-version: 14.19.1
        
    - name: install node tools
      run: npm install --global --production windows-build-tools
      
    - name: install node-gyp
      run: npm install --global node-gyp@latest

    - name: Install dependencies
      run: npm install
      
    - name: Build Renderer
      run: npm run build-renderer
      
    - name: Build Installer
      run: npm run build
